options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0 # TODO enable this
  no-important: 0 # this is unreasonable for existing projects
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - 'extra-properties':
      - 'scrollbar-width'
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0 # TODO this has got to go
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 2
  property-units: 0

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format: 0 # TODO study for BEM
  function-name-format: 2
  id-name-format: 2
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  attribute-quotes:
      - 2
      -
        include: true
  bem-depth: 2
  border-zero:
     - 2
     -
       convention: '0'
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 0  # TODO how does this work??
  property-sort-order: 0
  pseudo-element: 2
  quotes: 2
  shorthand-values:  #TODO these need to be translated to the shortest possible in the minifier
    - 2
    -
      allowed-shorthands:
        - 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2 #TODO why does the minifier not remove these??

  # Inner Spacing
  space-after-comma: 2
  space-before-colon:
    - 2
    -
      include: false
  space-after-colon: 2
  space-before-brace:
    - 2
    -
      include: true
  space-before-bang: 2
  space-after-bang: 0
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2